# Project Name
TARGET = QSPI

# Sources
CPP_SOURCES = QSPI.cpp

C_INCLUDES += \
-I./

DAISYSP_DIR = ../../../../DaisySP
LIBDAISY_DIR = ../../../../libDaisy

OPT = -Og

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

